In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
a[:, 0:-2]

array([[1],
       [4]])

In [7]:
b = np.array([1,2,3])
c = b[np.newaxis, :].T

In [9]:
c + np.array([1,1,1])

array([[2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [14]:
np.searchsorted([1, 2, 3], 1.1)

1

In [6]:
a, b,  *_ = 1, 2, 3, 4

In [7]:
a

1

In [8]:
_

[3, 4]

In [9]:
b

2